```R
# @param bstype_open     character, bootstrap type for open panels
# @param bstype_closed   character, bootstrap type for closed panels
.collapse_sidebar_set <- function(
  ...,
  id_set = NULL,
  width = 3,
  position = c("left", "right"),
  bstype_open = c("primary", "success", "info", "warning", "danger", "default"),
  bstype_closed = c("success", "info", "warning", "danger", "default", "primary")
){

  bstype_open <- match.arg(bstype_open)
  bstype_closed <- match.arg(bstype_closed)

}
```


# How collapse_panels work

A `collapse_sidebar_set` is composed of zero or more `collapse_sidebar_layout` elements

A `collapse_sidebar_layout` is composed of one `collapse_sidebar_panel` and one `collapse_sidebar_main` element

## Top layer

In this layer, we define the things that are bound together in the accordion arrangement.

At the top layer is the `collapse_sidebar_set()`. 

It has arguments:

```R
#' Matches things vertically 
#'
#' @param ...             `collapse_sidebar_layout` elements
#' @param id_set          character, identifier for the sidebar_collapse_set
#' @param width           integer, width (number of bootstrap columns) of the sidebar column
#' @param position        character, position of sidebar column "left", "right"
#' @param bstype_open     character, bootstrap type for open panels
#' @param bstype_closed   character, bootstrap type for closed panels
#'
#' @return `shiny::fluidRow()` where columns are defined below, depending on `position`  
#' @export
#
collapse_sidebar_set <- function(
  ..., 
  id_set, width = 3, position = "left", 
  bstype_open = "primary", bstype_closed = "success"){

  div_sidebar <- 
    shiny::tags$div(
      class = "panel-group"
      id = id_set,
      role = "tablist",
      aria-multiselectable = "true"
    )

  div_main <- shiny::tags$div() 
  
  # magic part where ... gets evaluated and put into the divs

  if (identical(position, "left")) {
  
    div_first <- div_sidebar
    width_first <- width
    
    div_second <- div_main
    width_second <- 12 - width
    
  } else if (identical(position, "right")){
  
    div_first <- div_main
    width_first <- 12 - width   
    
    div_second <- div_sidebar
    width_second <- width
  }

  shiny::fluidRow(
    shiny::column(width = width_first, div_first),
    shiny::column(width = width_second, div_second)
  )
}
```

Sidebar:

```
<div class="panel-group" id="{{id_set}}" role="tablist" aria-multiselectable="true">
  {{elements returned from the `collapse_sidebar_panel` within every `collapse_sidebar_layout`}}
</div>
```

Main:

```
<div>
  {{elements returned from the `collapse_main_panel` within every `collapse_sidebar_layout`}}
</div>
```

## Middle layer

In this layer, we define the matched sidebar and main layout elements

```R
#' Matches things horizontally
#'
#' The calling environment will be expected to provide:
#' - `id_set`
#' - `is_open`
#' - `bstype_open`
#'
#' The calling environment may provide 
#'  (but value sent via argument will have priority):
#'
#' - `bstype_closed`
#'
#' @param sidebar_collapse_panel  `sidebar_collapse_panel` element
#' @param main_collapse_panel     `main_collapse_panel` element
#' @param id_layout               character, identifier for the sidebar_collapse_layout
#' @param is_open                 logical, indicating if this element is initially open
#' @param bstype_open             character, bootstrap type for open panels
#' @param bstype_closed           character, bootstrap type for closed panels
#'
#' @return `sidebar_collapse_layout` list
#' @export
#
sidebar_collapse_layout <- function(
  sidebar_collapse_panel, 
  main_collapse_panel, 
  id_layout, 
  is_open = FALSE,
  bstype_open,
  bstype_closed){

  # magic to evaluate sidebar_collapse_panel, main_collapse_panel
  
  list(sidebar = sidebar, main = main)
}
```

A `sidebar_collapse_layout` is a list with two members: `sidebar` and `main`.

## Bottom Layer

### Sidebar

```R
#' builds a sidebar panel
#'
#' The calling environment will be expected to provide:
#' - `id_set`
#' - `id_layout`
#' - `is_open`
#' - `bstype_open`
#' - `bstype_closed`
#'
#' @param ...             UI elements to put into a `sidebar_collapse_panel` body 
#' @param title           stuff (coercible to HTML) to appear in panel-heading
#'                  
#' @return `htmltools::tags$div()`
#' @export
#'
sidebar_collapse_panel <- 
  function(..., title, id_set, id_layout, is_open, bstype_open, bstype_closed){

  # magic to evaluate ...


  panel_title <-
    htmltools::tags$h4(
      class = "panel-title",
      htmltools::tags$a(
        role = "button",
        data-toggle = "collapse",
        data-parent = "",
        href = "",
        aria-expanded = "",
        aria-controls = "",
        title
      )
    )
    
  panel_heading <- 
    htmltools::tags$div(
      class = "panel-heading",
      role = "tab",
      id = "",
      panel_title
    )
  
  panel_body <- 
    htmltools::tags$div(
      class = panel_body,
      ...
    )
  
  panel_collapse <-
    htmltools::tags$div(
      id = "",
      class = "",
      role = "tabpanel",
      aria-labelledby = "",
      panel_body
    )
  
  sidebar <-
    htmltools::tags$div(
      class = "",
      class-open = "",
      class-closed = "",
      id = "",
      panel_heading,
      panel_collapse
    )

  sidebar
}
```

`{{state}}` can be `true` or `false`
`{{in_state}}` can be `in` or ``
`{{if_empty}}` can be `padding-top: 0px; padding-bottom: 0px;` or ``

```
<div class="panel panel-{{bs_type}}" class-open="panel-{{bs_type_open}}" class-closed="panel-{{bs_type_closed}}" id="{{id_set}}_{{id_layout}}">
  <div class="panel-heading" role="tab" id="{{id_set}}_{{id_layout}}_heading">
    <h4 class="panel-title">
      <a role="button" data-toggle="collapse" data-parent="#{{id_set}}" href="#{{id_set}}_{{id_layout}}_collapse" aria-expanded="{{state}}" aria-controls="{{id_set}}_{{id_layout}}_collapse">
        {{title}}
      </a>
    </h4>
  </div>
  <div id="{{id_set}}_{{id_layout}}_collapse" class="panel-collapse collapse {{in_state}} panel-collapse-leader" role="tabpanel" aria-labelledby="{{id_set}}_{{id_layout}}_heading">
    <div class="panel-body" style="{{if_empty}}">
      {{...}}
    </div>
  </div>
</div>
```

### Main

```R
#' closure for `sidebar_collapse_main` 
#'
#' The calling environment will be expected to provide:
#' - `id_set`
#' - `id_layout`
#' - `is_open`
#' - `bstype_open`
#'
#' @param ...             UI elements to put into a `sidebar_collapse_main` body, 
#'                          if they are panels, then they can be composed using `{{bs_type}}`
#' 
#' @return div containing `sidebar_collapse_main` elements
#' @export
#
sidebar_collapse_main <- 
  function(..., id_set, id_layout, is_open, bstype_open){

  # magic to evaluate ...

  main <- 
    htmltools::tags$div(
      id = "",
      class = "",
      ...
    )

  main
}
```

Note that we can use `$("#id")` to identify elements with a given id

The function will return a `div`:

```
<div id="{{id_set}}_{{id_layout}}_collapse_follower" class="panel-collapse collapse {{in_state}}">
{{...}}
</div>
```

Keep in mind this example, as we build the closures.

```{r}
z <- 3

fn <- function(y, x = NULL){
  
  if (is.null(x)){
    x <- z
  }
  
  y + x
  
}
```





